### ISSUE TITLE
Deformable Image registration using simpleITK python framework

### ISSUE THREAD

**Issue by subhajitchatu** [InsightSoftwareConsortium/SimpleITK-Notebooks#117]
I am looking for deformable registrations using SimpleITK python framework.  

As in RegistrationITKV4 there are FEM based ( itkFEMRegistrationFilter.h) deformable registration and thin plate spline code is available, I was trying to figure out how to start using them in SimpleITK or python based platform. 

Demon registration is available in SimpleITK.

I need a sample code snippet for how to use FEM in simpleITK( python)

Thanks

**Comment by zivy** [comment]
Closing, as this issue was also opened and answered on the SimpleITK repository, SimpleITK/SimpleITK#118.
