### ISSUE TITLE
How to set 3D Slicer as viewer on Ubuntu 16.04

### ISSUE THREAD

**Issue by Thatfreesky** [InsightSoftwareConsortium/SimpleITK-Notebooks#120]
![image](https://cloud.githubusercontent.com/assets/15063337/25068034/e76480a4-2288-11e7-8983-21e2fd3320b0.png)

This statement just tell us how to set external viewer on MacOs, but how to do on Ubuntu 16.04.

**Comment by zivy** [comment]
The  [env command](https://ipython.org/ipython-doc/3/interactive/magics.html#magic-env) is an IPython magic, so it should work on all platforms. It is not specific to MacOS. Please replace the example path with the path to 3D Slicer on your system.

**Comment by Thatfreesky** [comment]
Thanks for your reply. I find those tutorials have no information about the 'xxx.mha' files. I know the SimpleITK and ITK packages can process those kind of files. But their no Pythonic documents are difficult for me to study. I find two ways to convert the 'xxx.mha' to 'xxx.nii' as below, then I can use the Nibabel to process it whose document are more user friendly.

**Convert the 'xxx.mha' to 'xxx.nii**
[By scikit-image](http://stackoverflow.com/questions/29738822/how-to-convert-mha-file-to-nii-file-in-python-without-using-medpy-or-c/31620239#31620239)
```python
import skimage.io as io

path = 'C:/test.mha' #path to your MHA file
outpath = 'C:/test.nii'

img = io.imread(path,plugin='simpleitk')
io.imsave('outpath',img,plugin='simpleitk')
```
[By medpy](http://pythonhosted.org/MedPy/tutorial/loadsave.html)
```python
>>> from medpy.io import load
>>> image_data, image_header = load('path/to/image.mha')

>>> from medpy.io import load, save
>>> save(image_data, 'path/to/image.nii', image_header)
```
So, my question is whether those ways can convert all information from 'xxx.mha' to 'xxx.nii'. If not, can you help me to solve this little problem, or recommend me some Pythonic SimpleITK reference.

Thank you very much!
P.S.: I am learning the [MICCAI BraTS](http://braintumorsegmentation.org/) challenge, whose data is '.mha' files.

**Comment by zivy** [comment]
@Thatfreesky,

As you observed, SimpleITK can read and write a variety of image formats. We use the file extension to identify the format for reading/writing.

To convert a file from mha to nii your SimpleITK program would look like this:
```
import SimpleITK as sitk
path = 'C:/test.mha' #path to your MHA file
outpath = 'C:/test.nii'

sitk.WriteImage(sitk.ReadImage(path), outpath)
```
Converting between other formats is just as easy. The only constraint is that you need to use the file extension.

**Comment by Thatfreesky** [comment]
Thanks for your help.
