### ISSUE TITLE
generate_random_pointset() function working in Registration_utilities.py

### ISSUE THREAD

**Issue by subhajitchatu** [InsightSoftwareConsortium/SimpleITK-Notebooks#124]
Hi,
To generate some random points inside the image only, we must ensure that we are taking points which have intensity value > 0. The input is a SimpleITK.Image. the domain or size does not ensure that the image has only nonzero pixel. Suppose we have a 512*512 image but the Field of view of the image is in 120*80 or may be it can not be depicted in rectangular tile. It may have a shape or different anatomy. So my question is we should check whether the pixel value is > 0 at that point.Right? Otherwise we may somehow skip relevant point. Though the whole 512*512 get registered. Still we will be interested on random points which are actually inside the image, I guess. How should we proceed in that case? 

Is there any bound of how many random points should we take for best results in suppose for 512*512? It is clear that we should not take a huge number of points from the set, it will nullify the registration error in some sense. (mean / SD). Please suggest.

Thanks

**Comment by zivy** [comment]
If you are interested in a subset of the image domain you can:
a. Provide a cropped image to the generate_random_pointset which only includes the region of interest or 
b. use a mask. One way to get a mask is via thresholding (selecting threshold>0 is an arbitrary threshold which doesn't necessarily relate to physical phenomena - select something appropriate for your data).

Please find below a function that uses a mask to provide a pointset in your region of interest and code that illustrates how to use it:

```
def generate_random_pointset_from_mask(image_mask, num_points):
    """
    Generate a random set (uniform sample) of points in the given mask domain.
    Note that the point set is limited to pixel/voxel locations.
    
    Args:
        image_mask (SimpleITK.Image): Domain in which points are created, only  
                                      use voxels whose value is equal to 1.
        num_points (int): Number of points to generate.
        
    Returns:
        A list of points (tuples). The number of points is either num_points or
        less if the number of mask voxels equal to 1 is smaller than num_points. 
    """
    npa_image_mask = sitk.GetArrayViewFromImage(image_mask)
    # Get all of the point indexes where the mask is set (we reverse this because numpy works in
    # z,y,x order)    
    all_point_indexes = np.stack(np.where(npa_image_mask==1)[::-1])
    random_point_indexes = all_point_indexes[:, np.random.randint(0, all_point_indexes.shape[1], 
                                                                  min(num_points, all_point_indexes.shape[1]))]
    
    pointset_list = (random_point_indexes.T).tolist()
    # Get the list of physical points corresponding to the indexes.
    return [image_mask.TransformContinuousIndexToPhysicalPoint(point_index) \
            for point_index in pointset_list]
```

Below we use this function to generate points that are inside the head. The mask is created by thresholding using the Hounsfield value for air. Please cut and paste the code below into a Jupyter notebook and you should see the result.

```
%run update_path_to_download_script
from downloaddata import fetch_data as fdata

import numpy as np
import SimpleITK as sitk

AIR_HU = -950 # it is actually -1000HU but the data is a bit noisy

fixed_image =  sitk.ReadImage(fdata("training_001_ct.mha"), sitk.sitkFloat32)
image_mask = fixed_image>AIR_HU

num_points = 100000

points = generate_random_pointset_from_mask(image_mask, num_points)

# quick and dirty way to visualize the point set
for p in points:
    fixed_image[fixed_image.TransformPhysicalPointToIndex(p)] = 3000 #Bone HU
sitk.Show(fixed_image)
```

**Comment by subhajitchatu** [comment]
Thanks a lot @zivy . 
Actually the problem with the masking is that, it is not only the case of noise but the image also has some other anatomical unwanted structure. So it becomes a segmentation problem. Which itself is very difficult. Is there any function to select a ROI interactively from the image and it will become a mask or cropped image after selecting the ROI and it will become  the input of the random set generating function.

Thanks

**Comment by zivy** [comment]
You can interactively select a single or multiple box shaped regions of interest using the ROIDataAquisition component found in the gui.py module. This is used in the [33_Segmentation_Thresholding_Edge_Detection](https://github.com/zivy/SimpleITK-Notebooks/blob/master/Python/33_Segmentation_Thresholding_Edge_Detection.ipynb) notebook.

The GUI allows you to select a rectangle on a slice and define the set of slices on which the rectangle is applied using a slider. This is a quick/coarse solution to your problem.

**Comment by subhajitchatu** [comment]
Thanks @zivy 

I have tried to run this api. but got the below error

In : from ipywidgets import interact, fixed

In : roi_acquisition_interface = ROIDataAquisition(original_image)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gui.py", line 510, in __init__
    rectprops = self.roi_display_properties)
TypeError: __init__() got an unexpected keyword argument 'interactive'

Package versions:

my python version : 2.7.9
Ubuntu 15.04
Jupyter version 4.3.0

Thanks

**Comment by zivy** [comment]
Given the [other issue you encountered](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/issues/124), there appears to be something wrong with your Python environment.

I would recommend creating a new virtual environment and installing the required packages using the requirements file we provide followed by activating the notebook extension. Please follow the Python related installation instructions we provide.
