### ISSUE TITLE
Feature based Registration in SimpleITK

### ISSUE THREAD

**Issue by subhajitchatu** [InsightSoftwareConsortium/SimpleITK-Notebooks#127]
Is there any function in SimpleITK to find intensity dependent as well independent features from a 3D image? OpenCV have functions for SIFT, SURF features etc but they all work in 2D images. I want these in 3D as well. If we have such feature extraction facility then it can also help us in segmentation or registration quality measurement.

Any comments?

Thanks

**Comment by zivy** [comment]
Yes it would be nice to have SIFT and SURF feature detectors in ITK and SimpleITK, they are indeed useful for registration/segmentation.

We currently do not have them in ITK and consequentially we don't have them in SimpleITK. It is unlikely that we will add them to ITK as it will potentially raise patent infringement issues (both algorithms are patented).

**Comment by subhajitchatu** [comment]
Ohk . Thanks @zivy . In case if you know any other way to find features in 3D images , please let me know. 
There are some other open source methods like [www.willowgarage.com/sites/default/files/orb_final.pdf](url) , which is an alternative to SURF and SIFT. We can look into this also.

Thanks.
