### ISSUE TITLE
Optimization Methods in SimpleITK

### ISSUE THREAD

**Issue by subhajitchatu** [InsightSoftwareConsortium/SimpleITK-Notebooks#129]
Hi @zivy ,

I have small doubts regarding optimization methods in reRistration

1. In SimpleITK , there is no Stochastic Gradient Descent or Adaptive SGD optimizer, is there any reason of skipping this method? I don't think for registering two image this algo would be helpful, I don't know, the algorithm tells about multiple samples optimization.

2. In ITK there are many more Optimizer like LM, Particle Swarm etc. itk::SPSAOptimizer, itk::ParticleSwarmOptimizerBase, itk::LBFGSBOptimizer , itk::CumulativeGaussianOptimizer, and itk::LevenbergMarquardtOptimizer.
But SimpleITK has not included these in its registration method class. Is there any way to access them via python?

Thanks

Subhajit

**Comment by zivy** [comment]
@subhajitchatu 

1. ITK and hence SimpleITK has a fixed set of optimizers. These work for most registration tasks and represent different algorithmic approaches to optimization  (gradient, gradient-free, evolutionary). There are many more optimization algorithms out there as this is an independent (and very interesting) research domain.

2. SimpleITK supports the ITKv4 registration framework and thus only the optimizers that are implemented there. The list of v4 optimizers can be found [here](https://itk.org/Insight/Doxygen/html/group__ITKOptimizersv4.html). ITK still contains the v3 registration framework with its optimizers which include ones that are not in v4.

**Comment by subhajitchatu** [comment]
Hi @zivy 

It's very Interesting. 

1. It is not clear then why v3 registration optimizers are still there, if most of the work can be done using only v4 registration framework.

2. As I can see there are two very useful optimizer in ITKv4 like MultiGradientOptimizerv4 , MultiStartOptimizerv4. I don't know whether these are implemented or not! But these are most interesting methods now a days. Anyway if these are also available in SimpleITK,  please let me know.

3. I am using SimpleITK in python 2.7, evolutionary methods are not showing up. Is there some version up-gradation required?

Thanks

**Comment by zivy** [comment]
@subhajitchatu 
The answer to question 1 is mostly historical reasons, part of the growth of ITK over the years.

The answer to question 2 is simply to [go to the doxygen documentation](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1ImageRegistrationMethod.html) and see the list of optimizers supported by simpleitk. This will always be the updated list.

Question 3, by evolutionary optimizers I meant the 1+1 optimizer which is supported in SimpleITK.

**Comment by subhajitchatu** [comment]
@zivy
Thanks!
I thought all ITKv4 methods will be supported in SimpleITK. Thats why I was excited when I saw MultiGradientOptimizerv4 , MultiStartOptimizerv4 in ITKv4. Because the initial guess problem can be solved via MultiStartOptimizerv4. 
Anyway 1+1 optimizer is not showing in my system's SimpleITK package. SimpleITK.py should have that function, even I did a "grep" in the SimpleITK directory , but couldn't able to to find . Thats why I asked you if there is version up-gradation required or not?

**Comment by zivy** [comment]
@subhajitchatu 

The multi start optimizer is essentially running the gradient descent multiple times based on multiple user initializations. This does not really solve the initialization challenge as the burden is still on the user to supply several initial transformations with the hope that one of them is close enough. If you want this feature added to SimpleITK, please [create an issue](https://github.com/SimpleITK/SimpleITK/issues) requesting it.  

The 1+1 optimizer was added in [release 1.0](https://github.com/SimpleITK/SimpleITK/releases/tag/v1.0.0). The ImageRegistrationMethod now has a SetOptimizerAsOnePlusOneEvolutionary method.

**Comment by subhajitchatu** [comment]
Hi @zivy 
Ok, I will surely create an issue, But I am also interested if SimpleITK could support multiple metric with weight parameter, because in many cases multiple metric usage is very helpful to avoid local minima or saddle point  problem in optimization. I don't know how much accurate MultiGradientOptimizerv4 is in this sense. Any suggestion?

Thanks
