### ISSUE TITLE
Deformable Registration doubts

### ISSUE THREAD

**Issue by subhajitchatu** [InsightSoftwareConsortium/SimpleITK-Notebooks#132]
Hi @zivy 

There are different deformable registrations which SimpleITK supports. I don't know if any other is supported. 

Lists are
DemonsRegistrationFilter, DiffeomorphicDemonsRegistrationFilter, FastSymmetricForcesDemonsRegistrationFilter, LevelSetMotionRegistrationFilter and SymmetricForcesDemonsRegistrationFilter

Can you please tell me some of my doubts

1. What are the basic differences of these methods? I mean in which cases we should use Diffeomorphic rather than only demon? I will be grateful if you can give me some good reference to get overview about these methods. 

2. Whats the actual role of matching point ? As I increase the number it doesn't effect the result.

3. How small RMS should be to declare it a good registration? Is there any limit we can put , then we can also bound number of iterations.

3. Is there any function which can display displacement field vectors pictorially, at least for one 2D slice?

Thanks

**Comment by subhajitchatu** [comment]
Hi @zivy ,

In general while we run demon registration it shows some metric measure for each iterations like
Eg.
sitk.SymmetricForcesDemonsRegistrationFilter()
--------
49 = 5442.87988
50 = 5435.78781
-------
Number Of Iterations: 50
 RMS: 0.79282342
----------------
sitk.FastSymmetricForcesDemonsRegistrationFilter
--------
49 = 7267.76
50 = 6900.65
-------
Number Of Iterations: 50
 RMS: 0.43282342
----------------

In the first case though metric value is lower than second but still RMS is higher. So can you tell me what it exactly signifies? and how to determine which one giving better registration?


2. I have come across an issue with sitk.LevelSetMotionRegistrationFilter().
   `matcher = sitk.HistogramMatchingImageFilter()
    matcher.SetNumberOfHistogramLevels(1024)
    moving = sitk.Resample(moving, fixed.GetSize(), sitk.Transform() , interpolator, fixed.GetOrigin(), fixed.GetSpacing() , fixed.GetDirection())
    matcher.SetNumberOfMatchPoints(7)
    matcher.ThresholdAtMeanIntensityOn()
    moving = matcher.Execute(moving,fixed)
    demons = sitk.LevelSetMotionRegistrationFilter()
    demons.SetNumberOfIterations(50)
    demons.SetGradientSmoothingStandardDeviations(1)
    demons.AddCommand( sitk.sitkIterationEvent, lambda: command_iteration_demon(demons) )

     displacementField = demons.Execute(fixed, moving)`

As it doesn't require initial transformation and displacement field filter, so I have skipped that and goes with default values.

But the GetElapsedIterations() and GetMetric() are showing 

0 = 0.0000
0 = 0.0000

can you please tell, how to use this function?  
    
Thanks

**Comment by zivy** [comment]
@subhajitchatu 

All good questions. To understand the differences between all of the registration methods you looked at you will have to read the publications which describe them or a survey paper.

If your goal is to use a non-rigid registration method to solve a clinical problem then any method which is sufficiently accurate should be good enough.

If your goal is to write a paper comparing registration methods for a specific task (register modalityA to modalityB using transformTypeA) then you may find one of the methods is optimal.
In general, if you don't have prior knowledge about the optimized function (modalityA, modalityB, transformTypeA) the no-free lunch theorem says that there is no best algorithm. See the paper [here](https://ti.arc.nasa.gov/m/profile/dhw/papers/78.pdf).

With regard to all of the Demons based methods those are intended for intra-modal registration such as CT/CT. Looking at resulting RMS values just tells you which result is expected to be better aligned. This may not be correct. That is, it is possible to have a registration with lower RMS but the alignment is worse.

**Comment by subhajitchatu** [comment]
Thanks @zivy
You pointed out two very interesting points. 
One is all demon algorithms are intended for intramodal , but when I was using demon algorithms for MRI T2 and PDw , it was working well. They are treated as inter modal registration. Now I am little confused to see this behavior. So you are saying there are no deformable registration methods for inter modalities? 
Secondly suppose we know  method A is giving lower RMS than method B for same image pair , which is a notation of error. Right? So doesn't it mean method A is better?
The terminology of RMS for demon registration, and metric values for other methods are confusing. So you are telling there is no correlation with registration accuracy and metric or RMS? It's just a number during computation. No conclusion can be derived from this number. Right?

Thanks

**Comment by zivy** [comment]
@subhajitchatu 

multi-modal non-rigid registration: Use FFD as shown in [this notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/65_Registration_FFD.ipynb) with the appropriate metric (correlation or ANTSNeighborhoodCorrelation or JointHistogramMutualInformation or MattesMutualInformation).

A lower similarity metric value (in this case RMS) does not necessarily mean better registration. I strongly suggest that you read the relevant literature before you continue with your work. Relevant starting points:
1. [RIRE](http://www.insight-journal.org/rire/)
2. [NIREP](http://www.nirep.org/introduction)
3. Ying Wei's [masters thesis](http://ir.uiowa.edu/cgi/viewcontent.cgi?article=1633&context=etd) from U. Iowa.
4. google: "non-rigid registration evaluation"
