### ISSUE TITLE
Mattes Mutual Information basic doubts

### ISSUE THREAD

**Issue by subhajitchatu** [InsightSoftwareConsortium/SimpleITK-Notebooks#133]
Hi @zivy 

1. Can you please tell , whether Mattes Mutual information is a maximizing function or minimizing function.
Metric Mattes Mutual Info and Gradient Descent Optimizer
output was like
************
numofbins = 30
Optimizer stop condition: RegularStepGradientDescentOptimizerv4: Step too small after 24 iterations. Current step (7.62939e-06) is less than minimum step (1e-05).
 Iteration: 25
 Metric value: -0.871268982129

************
numofbins = 4096
Optimizer stop condition: RegularStepGradientDescentOptimizerv4: Step too small after 34 iterations. Current step (7.62939e-06) is less than minimum step (1e-05).
 Iteration: 23
 Metric value: -1.7890
************

If it is a minimization function then the lower one is better, which I suspect.

2.
 TranslationTransform (0x44fbd20)
   RTTI typeinfo:   itk::TranslationTransform<double, 3u>
   Reference Count: 2
   Modified Time: 5528423

What do we mean by Modified Time?

Thanks

**Comment by zivy** [comment]
Hi @subhajitchatu 

All metrics in the v4 registration metric are set for minimization. Those whose optimum corresponds to a maximum are internally negated so that the optimizers can always minimize. This is the case for mutual information whose optimum is at the maximal value.
