### ISSUE TITLE
Mutual Information metric in Deformable registrations

### ISSUE THREAD

**Issue by subhajitchatu** [InsightSoftwareConsortium/SimpleITK-Notebooks#135]
Hi,
@zivy 

I went through some papers on Deformable registration which includes demon registration, diffeomorphic and fastSymmetric registration. Finally I have realized that these are generally used for intra-modal registration because metrics are derived from image differences which depends on the intensity(SSD and Optical flow concepts). But if we follow the same mathematical calculation with Mutual information, it will also work and eventually it will be applicable to multi-modal registrations also. In SimpleITK we have demon as metric and different filters for deformable registrations. But they are not capable of changing metric type.

I have seen AnTs has support(derived from ITKv4?) for changing metric to MI,CC with regularization Gauss,DMFFD and transformation Elastic,Symmetric etc. 

Is there any way to change metric to MI in demon registration algorithm in SimpleITK also? I have not seen ITK's code, so I don't have idea whether it supports or not?

Thanks

**Comment by myronzbrown** [comment]
Hi. I am looking for the same thing and don't see it in sitk now. Did you find an answer for this or an alternative? From experimenting with the sitk registration methods, demons appears to significantly outperform the other metrics for producing a well-regularized deformation field. Using ImageRegistrationMethod.SetMetricAsDemons or the four specific filters (e.g. FastSymmetricForcesDemonsRegistrationFilter), the result I get is well regularized if I specify a large Gaussian smoothing value. For the other metrics, I see fast deformations even if I set the variance very high. I am hoping to do a direct comparison of demons with squared error vs. mutual information. Any tips you could share?

Thanks,

**Comment by zivy** [comment]
Dear @myronzbrown,
You posted your question in a closed issue. In the future, please (re) open an issue or ask on [ITK discourse](https://discourse.itk.org/).
 
With respect to the question, not clear to me what exactly it is that you are asking. What registration setups (optimizer-similiarity metric- inter/intra modal) do you want to compare?

**Comment by pubgeo** [comment]
Thanks @zivy. Sorry. I will do that in the future. I was hoping to roughly reproduce in python the inter-modal alignment results I get in MATLAB using demons with the mutual information metric. I can get roughly that for inter-modal case in sitk, and it works pretty well for intra-modal image pairs if I apply a Laplacian of Gaussian filter on the images first, but i was hoping to get a direct comparison with mutual information. Not urgent, but it seems like something that would come up from time to time so I wanted to ask if I'm missing something that's already available.

**Comment by zivy** [comment]
Hello @pubgeo,
No worries. You are not missing something that is available. SimpleITK doesn't have a MI based Demons registration.
