### ISSUE TITLE
example of 2D registration

### ISSUE THREAD

**Issue by fabien-w** [InsightSoftwareConsortium/SimpleITK-Notebooks#148]
Hi, 
First of all thank you very much for this notebook. I have test almost all the function with R and it works very well.
I am trying to make a 2D image registration in R with SimpleITK on Linux and i was wondering if you plan to make an example for 2D registration with .png images. I work with aerial remote sensing image and i am particularly interest with the Diffeomorphic demons registration for two image with one presenting distortion due the plane movement.
I have try some of your function for registration with simulated 2D image  but I didn't manage to make it work. It would be very nice to have a simple example such as the Figure 5 of "Diffeomorphic Demons:  Efficient Non-parametric Image Registration" of Tom Vercauteren et al (http://www-sop.inria.fr/asclepios/Publications/Tom.Vercauteren/DiffeoDemons-NeuroImage08-Vercauteren.pdf)

here is how I have generate two square with some difference in size to further make a registration of one wit the other, in case it could help

library(raster)
library(imager)
r=raster(ncol=256,nrow=256)
r=setValues(r,0)
im1=as.cimg(r)
im1[125:150,125:150]=255
plot(im1)

im2=as.cimg(r)
im2[130:170,130:170]=255
plot(im2)

save.image(im1,"square1.png")
save.image(im2,"square2.png")

Thank you very much,

Fabien

**Comment by zivy** [comment]
Hello Fabian,

We are currently not planning to write a specific example for the 2D case as the Demons registration notebook covers the required components.

Having said that, I isolated the relevant snippets from that notebook and created [a gist](https://gist.github.com/zivy/fb7af293d877c70f188acc2240bcb5a4) illustrating the use of the Diffeomorphic Demons algorithm to register two rectangles. This did require the use of a multi-resolution scheme as the registration was not successful when using the original resolution. Also, the result is less than ideal, but that requires additional tweeking of the registration parameters (both demons and pyramid).

Let me know if this answers your question and I will close the issue.
    Ziv

**Comment by fabien-w** [comment]
Dear Ziv Yaniv,
Thank you very much for the code, this answer totally my question. you can
close the issue. i will now try to adapt the code for my research.
Cheers,
Fabien



2017-08-29 16:44 GMT-03:00 Ziv Yaniv <notifications@github.com>:
