### ISSUE TITLE
Registration using PyCharm

### ISSUE THREAD

**Issue by nunoloucao** [InsightSoftwareConsortium/SimpleITK-Notebooks#155]
Hi,

I'm using PyCharm for 3D registration with Dicom data, and i'm having some problems in the final steps because of the registration_callbacks:

Traceback (most recent call last):
  File "/Users/nunoloucao/PycharmProjects/Teste_simpleitk/teste_ITK.py", line 19, in <module>
    import registration_callbacks
ModuleNotFoundError: No module named 'registration_callbacks'

i can't find it in any library.

thanks,
Nuno

**Comment by zivy** [comment]
Hello @nunoloucao,

The [registration_callbacks module](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/registration_callbacks.py) is part of the [SimpleITK notebooks repository](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks), so you will need to get it from there. The repository contains other useful modules such as registration_utilities.py and gui.py.

hope this helps
       Ziv
