### ISSUE TITLE
Unable to download packages gui

### ISSUE THREAD

**Issue by Skp80** [InsightSoftwareConsortium/SimpleITK-Notebooks#181]
Hi,

I am trying to run the following example on simpleITK on the segmentation - https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/300_Segmentation_Overview.ipynb

There are few packages - myshow and Gui...etc. I am not able to find them on Pypi or any other python repos. Can you please advise where to import them from.
from myshow import myshow, myshow3d

**Comment by blowekamp** [comment]
They are include with this repository. Please clone the repository and follow the instructions here:
https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/tree/master/Python
