### ISSUE TITLE
ModuleNotFoundError: No module named '_SimpleITK'

### ISSUE THREAD

**Issue by adamcon** [InsightSoftwareConsortium/SimpleITK-Notebooks#193]
I installed sitkpy via: `conda env create -f environment.yml` and then tried importing via ipython:
`import SimpleITK as sitk`
and got the error:

```Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.0.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import SimpleITK as sitk
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\envs\sitkpy\lib\site-packages\SimpleITK\SimpleITK.py in swig_import_helper()
     13         try:
---> 14             return importlib.import_module(mname)
     15         except ImportError:

~\AppData\Local\Continuum\anaconda3\envs\sitkpy\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127

~\AppData\Local\Continuum\anaconda3\envs\sitkpy\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

~\AppData\Local\Continuum\anaconda3\envs\sitkpy\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

~\AppData\Local\Continuum\anaconda3\envs\sitkpy\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

~\AppData\Local\Continuum\anaconda3\envs\sitkpy\lib\importlib\_bootstrap.py in _load_unlocked(spec)

~\AppData\Local\Continuum\anaconda3\envs\sitkpy\lib\importlib\_bootstrap.py in module_from_spec(spec)

~\AppData\Local\Continuum\anaconda3\envs\sitkpy\lib\importlib\_bootstrap_external.py in create_module(self, spec)

~\AppData\Local\Continuum\anaconda3\envs\sitkpy\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-083a0dc1974c> in <module>
----> 1 import SimpleITK as sitk

~\AppData\Local\Continuum\anaconda3\envs\sitkpy\lib\site-packages\SimpleITK\__init__.py in <module>
----> 1 from .SimpleITK import *

~\AppData\Local\Continuum\anaconda3\envs\sitkpy\lib\site-packages\SimpleITK\SimpleITK.py in <module>
     15         except ImportError:
     16             return importlib.import_module('_SimpleITK')
---> 17     _SimpleITK = swig_import_helper()
     18     del swig_import_helper
     19 elif _swig_python_version_info >= (2, 6, 0):

~\AppData\Local\Continuum\anaconda3\envs\sitkpy\lib\site-packages\SimpleITK\SimpleITK.py in swig_import_helper()
     14             return importlib.import_module(mname)
     15         except ImportError:
---> 16             return importlib.import_module('_SimpleITK')
     17     _SimpleITK = swig_import_helper()
     18     del swig_import_helper

~\AppData\Local\Continuum\anaconda3\envs\sitkpy\lib\importlib\__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127
    128

ModuleNotFoundError: No module named '_SimpleITK'
```

Does anyone know how to install SimpleITK properly? (I had the same issue with `pip install SimpleITK` , `conda install -c simpleitk simpleitk`)! Running anaconda3 on Windows 64...

**Comment by zivy** [comment]
To allow us to reproduce the problem, please export your conda environment to a "problem_env.yml" file and post here. See the conda guide for [instructions on exporting](https://conda.io/docs/user-guide/tasks/manage-environments.html#sharing-an-environment).

**Comment by adamcon** [comment]
Hi Ziv, please see the attached problem_env.yml (pasted underneath in case of firewalls etc)
Regards,
Adam

name: sitkpy
channels:
  - simpleitk
  - defaults
  - conda-forge
dependencies:
  - icu=58.2=vc14_0
  - jpeg=9b=vc14_2
  - libpng=1.6.34=vc14_0
  - libtiff=4.0.9=vc14_0
  - openssl=1.0.2o=vc14_0
  - sqlite=3.22.0=vc14_0
  - zlib=1.2.11=vc14_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=2.1.4=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.24=py36_1
  - colorama=0.3.9=py36h029ae33_0
  - cycler=0.10.0=py36h009560c_0
  - decorator=4.3.0=py36_0
  - entrypoints=0.2.3=py36_2
  - freetype=2.9.1=ha9979f8_1
  - html5lib=1.0.1=py36_0
  - icc_rt=2017.0.4=h97af966_0
  - intel-openmp=2019.0=118
  - ipykernel=5.0.0=py36h39e3cac_0
  - ipython=7.0.1=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h3c5d0ee_0
  - ipywidgets=7.4.2=py36_0
  - jedi=0.12.1=py36_0
  - jinja2=2.10=py36_0
  - jsonschema=2.6.0=py36h7636477_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36_1
  - jupyter_core=4.4.0=py36_0
  - kiwisolver=1.0.1=py36h6538335_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.0=py36hfa6e2cd_1
  - matplotlib=3.0.0=py36hd159220_0
  - mistune=0.8.3=py36hfa6e2cd_1
  - mkl=2019.0=118
  - mkl_fft=1.0.6=py36hdbbee80_0
  - mkl_random=1.0.1=py36h77b88f5_1
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.3.1=py36_0
  - nbformat=4.4.0=py36h3a5bc1b_0
  - notebook=5.7.0=py36_0
  - numpy=1.15.2=py36ha559c80_0
  - numpy-base=1.15.2=py36h8128ebf_0
  - pandas=0.23.4=py36h830ac7b_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.3.1=py36_0
  - pickleshare=0.7.5=py36_0
  - pip=10.0.1=py36_0
  - prometheus_client=0.4.0=py36_0
  - prompt_toolkit=2.0.5=py36_0
  - pygments=2.2.0=py36hb010967_0
  - pyparsing=2.2.1=py36_0
  - pyqt=5.9.2=py36h1aa27d4_0
  - python=3.6.6=hea74fb7_0
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.5=py36_0
  - pywinpty=0.5.4=py36_0
  - pyzmq=17.0.0=py36hfa6e2cd_0
  - qt=5.9.4=vc14hd9fb3db_0
  - qtconsole=4.4.1=py36_0
  - scipy=1.1.0=py36h4f6bf74_1
  - send2trash=1.5.0=py36_0
  - setuptools=40.4.3=py36_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.8=py36h6538335_0
  - six=1.11.0=py36_1
  - terminado=0.8.1=py36_1
  - testpath=0.4.2=py36_0
  - tornado=5.1.1=py36hfa6e2cd_0
  - traitlets=4.3.2=py36h096827d_0
  - vc=14=h0510ff6_3
  - vs2015_runtime=14.15.26706=h3a45250_0
  - wcwidth=0.1.7=py36h3d5aa90_0
  - webencodings=0.5.1=py36_1
  - wheel=0.32.0=py36_0
  - widgetsnbextension=3.4.2=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - winpty=0.4.3=4
  - simpleitk=1.1.0=py36h6538335_0
  - pip:
    - ipacs-pusher==0.1
    - pypiwin32==223
prefix: C:\Users\aconnol\AppData\Local\Continuum\anaconda3\envs\sitkpy

**Comment by zivy** [comment]
@adamcon,
Thanks for providing the yml file. Unfortunately, I am getting a ResolvePackageNotFound error listing a large number of packages. These possibly may not be available or the specific version isn't available for my specific machine (os x).

I saw you have conda-forge as a channel. We have compatibility issues with packages downloaded from there instead of directly from the default anaconda channel. Likely that is the issue. 

Can you try and create an environment only with SimpleITK and see if it works? In the past when I didn't pin specific versions I had them clobbered by newer versions of packages from conda-forge which created package in-compatibility issues.

**Comment by zivy** [comment]
Closing the issue, feel free to open the issue if the problem persists.
