### ISSUE TITLE
Slice mismatch problem in 3D MRI registration

### ISSUE THREAD

**Issue by bnsmita** [InsightSoftwareConsortium/SimpleITK-Notebooks#199]
Hi,

I have tried to register two 3D stack of images using SimpleITK Affine Registration method. But it failed to register the moving image with the fixed image.
The problem is that there is slice mismatch in the fixed and moving images.

For eg.  slice no. 6 of fixed image matches with slice no. 7 of moving image. But the total number of slices in both images are 12.
Also there is movement in slices when I compare fixed with output image.

I have used the following code to register these two images
`def GlobalAffineRegistration(fixed_image,moving_image):

    initial_transform = sitk.CenteredTransformInitializer(sitk.Cast(fixed_image,sitk.sitkFloat32), 
                                                                                       sitk.Cast(moving_image,sitk.sitkFloat32), 
                                                                                       sitk.AffineTransform(3),
                                                                                       sitk.CenteredTransformInitializerFilter.GEOMETRY)

  
    # Perform simplest (single level) registration
    registration_method = sitk.ImageRegistrationMethod()
    registration_method.SetMetricAsMattesMutualInformation(numberOfHistogramBins=32)
    registration_method.SetInterpolator(sitk.sitkLinear)
    registration_method.SetOptimizerAsGradientDescent(learningRate=1.0, numberOfIterations=300, convergenceMinimumValue=1e-6, convergenceWindowSize=10)
    registration_method.SetOptimizerScalesFromPhysicalShift()
    registration_method.SetInitialTransform(initial_transform, inPlace=False)
    final_transform = registration_method.Execute(sitk.Cast(fixed_image,sitk.sitkFloat32) , sitk.Cast(moving_image,sitk.sitkFloat32))
     out = sitk.Resample(moving, fixed, final_transform, sitk.sitkLinear, 0.0, moving.GetPixelID())			
      sitk.WriteImage(out,outFileName)

I have attached the fixed, moving and output image respectively in a .zip file for a better understanding of my problem.
Moreover when I was using MATLAB imregister function, it was able to detect slice mismatch and take care of it. Please suggest what type of method or parameter setting should I use to get rid of this type of problem.

[outImage.zip](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/files/2729361/outImage.zip)

**Comment by zivy** [comment]
Hello @bnsmita,

There is a bug in the code you posted. Notice that you refer to `fixed_image` and `moving_image` when calling `registration_method.Execute`. When you call `sitk.Resample` you refer to `moving` and `fixed`, so  these are different images that you are looking at (the code just exits with an error `NameError: name 'moving' is not defined`).

After this minor fix the code appears to work (visual inspection shows reasonable alignment).

Some things to note:
1. If all you are doing is registration you can just read the images and cast to float as part of the reading.
2. Always print the reason for termination of the optimizer during the development process.

Below is the code I ran:
```
import SimpleITK as sitk


fixed_image = sitk.ReadImage('outImage/fixed.nii', sitk.sitkFloat32)
moving_image = sitk.ReadImage('outImage/moving.nii', sitk.sitkFloat32)

initial_transform = sitk.CenteredTransformInitializer(fixed_image,
                                                      moving_image,
                                                      sitk.AffineTransform(3),
                                                      sitk.CenteredTransformInitializerFilter.GEOMETRY)

resampled_moving = sitk.Resample(moving_image, fixed_image, initial_transform)

sitk.Show(fixed_image, 'fixed_image')
sitk.Show(resampled_moving, 'initial_resampled_moving_image')


registration_method = sitk.ImageRegistrationMethod()
registration_method.SetMetricAsMattesMutualInformation(numberOfHistogramBins=32)
registration_method.SetInterpolator(sitk.sitkLinear)
registration_method.SetOptimizerAsGradientDescent(learningRate=1.0, numberOfIterations=300, convergenceMinimumValue=1e-6, convergenceWindowSize=10)
registration_method.SetOptimizerScalesFromPhysicalShift()
registration_method.SetInitialTransform(initial_transform, inPlace=False)
final_transform = registration_method.Execute(fixed_image , moving_image)
print(registration_method.GetOptimizerStopConditionDescription())

out = sitk.Resample(moving_image, fixed_image, final_transform, sitk.sitkLinear, 0.0, moving_image.GetPixelID())

sitk.Show(out, 'final_resampled_moving_image')
```

**Comment by bnsmita** [comment]
Hello @zivy 

Thank you!
I tried the above code you ran. It is working fine for the previous data with slight mismatch in slices. I am attaching here another image data where there is huge slice mismatch. I have also tried affine registration, b-spline method registration, the issue still persists. If you can recommend any other registration function which can be more appropriate for solving slice mismatch issue , would be very helpful. 
[fixed.zip](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/files/2736922/fixed.zip)

[moving.zip](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/files/2736923/moving.zip)
[output.zip](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/files/2736924/output.zip)

**Comment by zivy** [comment]
Hello @bnsmita,

The changes you are making will not solve the issue you are experiencing. You are changing the type of transformation and that is not the issue with the data you provided. The challenge with your new dataset is that the images have about 50% overlap. The fixed image contains the bottom portion of the head and the moving the top portion and the shared region is about 50%. This means that when we initialize using the center of the volumes the corresponding regions are far from each other. You need to be very lucky for optimization to succeed in such a case.

If these datasets represent the variability you will encounter in your work then you will need to use a more robust initialization approach. For a list of possible options and examples see [this Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/63_Registration_Initialization.ipynb).
