### ISSUE TITLE
Need an example to show 2D image registration in Python

### ISSUE THREAD

**Issue by mit10000** [InsightSoftwareConsortium/SimpleITK-Notebooks#211]
Thanks for sharing!

We noticed there is 3D volumes registration. Is there any example to simply show how to do two 2D images registration? No doubt this is the 1st experiment people want to try.

**Comment by zivy** [comment]
The same code should work for 2D images, as is. The basic example in [this notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/60_Registration_Introduction.ipynb) doesn't take into account the dimensionality of the images other than in the display functions that can be commented out. All that you need to do is read your 2D images: 
```
fixed_image = sitk.ReadImage('my_2d_image_file.jpg', sitk.sitkFloat32)
moving_image = sitk.ReadImage('my_other_2d_image_file.jpg', sitk.sitkFloat32)
```

**Comment by mit10000** [comment]
@zivy Thanks for your reply.
We tried to read in 2D images, and in this step 

initial_transform = sitk.CenteredTransformInitializer(fixed_image, 
                                                      moving_image, 
                                                      sitk.Euler3DTransform(), 
                                                      sitk.CenteredTransformInitializerFilter.GEOMETRY)

Got error:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-5b8c2b162783> in <module>()
      2                                                       moving_image,
      3                                                       sitk.Euler3DTransform(),
----> 4                                                       sitk.CenteredTransformInitializerFilter.GEOMETRY)
      5 
      6 #moving_resampled = sitk.Resample(moving_image, fixed_image, initial_transform, sitk.sitkLinear, 0.0, moving_image.GetPixelID())

~/anaconda3/lib/python3.6/site-packages/SimpleITK/SimpleITK.py in CenteredTransformInitializer(*args, **kwargs)
   9669 
   9670     """
-> 9671     return _SimpleITK.CenteredTransformInitializer(*args, **kwargs)
   9672 class CenteredVersorTransformInitializerFilter(ProcessObject):
   9673     """

RuntimeError: Exception thrown in SimpleITK CenteredTransformInitializer: /tmp/SimpleITK/Code/BasicFilters/src/sitkCenteredTransformInitializerFilter.cxx:102:
sitk::ERROR: Transform parameter for CenteredTransformInitializerFilter doesn't match dimension!

**Comment by zivy** [comment]
I overlooked the transform type which was specific to 3D, please change it to sitk.Euler2DTransform().

**Comment by zivy** [comment]
Closing the issue. Please reopen if the answer did not resolve the problem.
