### ISSUE TITLE
 change the default external viewer to 3D Slicer,sitk::ERROR: Unable to determine ImageIO reader

### ISSUE THREAD

**Issue by jumbojing** [InsightSoftwareConsortium/SimpleITK-Notebooks#235]
%env SITK_SHOW_COMMAND /Applications/Slicer.app/Contents/MacOS/Slicer
sitk.Show(sitk.ReadImage(fetch_data("SimpleITK.jpg")), "SimpleITK Logo", debugOn=True)

<pre>
env: SITK_SHOW_COMMAND=‘/Applications/Slicer.app/Contents/MacOS/Slicer’
Fetching SimpleITK.jpg
</pre>

<pre>
---------------------------------------------------------------------------RuntimeError                              Traceback (most recent call last)
<ipython-input-8-29a6db46f6a8> in <module>
      1 \# Uncomment the line below to change the default external viewer to your viewer of choice and test that it works.
      2 get_ipython().run_line_magic('env', 'SITK_SHOW_COMMAND ‘/Applications/Slicer.app/Contents/MacOS/Slicer’')
----> 3 sitk.Show(sitk.ReadImage(fetch_data("SimpleITK.jpg")), "SimpleITK Logo", debugOn=True)

~/anaconda3/lib/python3.7/site-packages/SimpleITK/SimpleITK.py in ReadImage(*args)
   8874 
   8875     """
-> 8876     return _SimpleITK.ReadImage(\*args)
   8877 class ImageViewer(_object):
   8878     """

RuntimeError: Exception thrown in SimpleITK ReadImage: ../../Code/IO/src/sitkImageReaderBase.cxx:107:
sitk::ERROR: Unable to determine ImageIO reader for "/Users/apple/Documents/GitHub/SimpleITK-Notebooks-master/Data/SimpleITK.jpg"
</pre>

**Comment by zivy** [comment]
I believe this issue was resolved, so closing. If this is incorrect please feel free to reopen.
