### ISSUE TITLE
is it a error or bug in external view with 3d slicer?

### ISSUE THREAD

**Issue by jumbojing** [InsightSoftwareConsortium/SimpleITK-Notebooks#236]
when i run follow code:

```sitk.Show(sitk.ReadImage(fetch_data("SimpleITK.jpg")), "SimpleITK Logo")```

3DSlicer startup, load and display the SimpleITK.jpg, but this cell keep freezing, and “the debug information” in the terminal is:

```Debug: In C:\Users\dashboard\Miniconda3-32\conda-bld\simpleitk_1546469625090\work\Code\IO\src\sitkShow.cxx, line 514: Show command: 'C:\Program' 'Files\Slicer' '4.9.0-2017-10-31\Slicer.exe' 'C:\\Users\\1\\AppData\\Local\\Temp\\SimpleITKLogo-7880-0.nii'
```
where is the sitkShow.cxx, where is the "\dashboard\Miniconda3-32\..."? I can't find them.

en....I delete "debugOn=True", this cell still keep freezing([IN(*)])....

is it a error or bug？

**Comment by jumbojing** [comment]
“the debug information” in the terminal is:

``` Debug: In C:\Users\dashboard\Miniconda3-32\conda-bld\simpleitk_1546469625090\work\Code\IO\src\sitkShow.cxx, line 514: Show command: 'C:\Program' 'Files\Slicer' '4.9.0-2017-10-31\Slicer.exe' 'C:\\Users\\1\\AppData\\Local\\Temp\\SimpleITKLogo-7880-0.nii'```

**Comment by blowekamp** [comment]
Are you using SimpleITK version 1.2.2?

**Comment by jumbojing** [comment]
> Are you using SimpleITK version 1.2.2?

> SimpleITK Version: 1.2.0 (ITK 4.13)

In China, we couldn't update SITK in conda...

**Comment by blowekamp** [comment]
This is a known bug in 1.2.0 that was addressed in 1.2.2.
