### ISSUE TITLE
sitk.GetArrayFromImage and sitk.GetImageFromArray

### ISSUE THREAD

**Issue by luckyxiaoqi** [InsightSoftwareConsortium/SimpleITK-Notebooks#244]
I use simpleITK read a image(.nii format),then I transform it to array,and again transform array into image, then I found something has changed,why this happen?
code
import numpy as np
import SimpleITK as sitk

itk_img=sitk.ReadImage('AD_001/AD_001.nii')
print(itk_img)
print(itk_img.GetSize())
print(itk_img.GetSpacing())
img=sitk.GetArrayFromImage(itk_img)
itk_img1=sitk.GetImageFromArray(img)
print(itk_img1.GetSpacing())
print(itk_img1.GetSize())
#itk_img1.SetSpacing(itk_img.GetSpacing())
#itk_img1.SetOrigin(itk_img.GetOrigin())
print(itk_img1)

the part of result
Image (0x27df6e0)
  RTTI typeinfo:   itk::Image<unsigned short, 3u>
  Reference Count: 1
  Modified Time: 965
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 942
  UpdateMTime: 964
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [176, 240, 256]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [176, 240, 256]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [176, 240, 256]
  Spacing: [1.2, 1, 1]
  Origin: [-138, -135, 376]
  Direction: 
-1 0 0
0 -1 0
0 0 1

  IndexToPointMatrix: 
-1.2 0 0
0 -1 0
0 0 1

  PointToIndexMatrix: 
-0.833333 0 0
0 -1 0
0 0 1

  Inverse Direction: 
-1 0 0
0 -1 0
0 0 1

  PixelContainer: 
    ImportImageContainer (0x275e3c0)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, unsigned short>
      Reference Count: 1
      Modified Time: 961
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x7fa41d482010
      Container manages memory: true
      Size: 10813440
      Capacity: 10813440

(176, 240, 256)
(1.1999999284744263, 1.0, 1.0)
(1.0, 1.0, 1.0)
(176, 240, 256)
Image (0x2776bf0)
  RTTI typeinfo:   itk::Image<unsigned short, 3u>
  Reference Count: 1
  Modified Time: 973
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 0
  UpdateMTime: 0
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [176, 240, 256]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [176, 240, 256]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [176, 240, 256]
  Spacing: [1.2, 1, 1]
  Origin: [-138, -135, 376]
  Direction: 
1 0 0
0 1 0
0 0 1

  IndexToPointMatrix: 
1.2 0 0
0 1 0
0 0 1

  PointToIndexMatrix: 
0.833333 0 0
0 1 0
0 0 1

  Inverse Direction: 
1 0 0
0 1 0
0 0 1

  PixelContainer: 
    ImportImageContainer (0x2709b50)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, unsigned short>
      Reference Count: 1
      Modified Time: 970
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x43c8260
      Container manages memory: true
      Size: 10813440
      Capacity: 10813440

**Comment by ljjiayou** [comment]
I also met this problem. Have you solved it？
