### ISSUE TITLE
Error when running Jupyter Notebooks Fetch Data

### ISSUE THREAD

**Issue by paulomontijo** [InsightSoftwareConsortium/SimpleITK-Notebooks#254]
Hello,

i am having some problems while trying to load data using the Simple ITK Jupyter Notebooks. I have internet connection and I have alrealdy loaded the data from other notebooks using the same process. In the specific Registration notebooks (61, 62 and 63 so far) I get the following error when trying to load the CIRS057A_MR_CT_DICOM data:

![image](https://user-images.githubusercontent.com/43051367/78362388-4af29480-75ba-11ea-853e-225ce5a156aa.png)

The readme.txt does not exist in the directory as I checked.

Can someone help me, please?

**Comment by zivy** [comment]
Hello @paulomontijo,

There may have been an issue during the download (failure in the middle), so I suggest trying to download again. 

Before you do that, please go into the Data directory and see if there is a sub-directory named CIRS057A_MR_CT_DICOM. If it exists, delete it and then try running the notebook again (it will attempt to download the data from our servers). Finally, make sure that you have enough disk space on your machine. The notebooks data is about 2Gb.

**Comment by paulomontijo** [comment]
Hello @zivy,

Thanks for the support. I tried deleteing the empty folder I had CIRS057A_MR_CT_DICOM, which still incurred on the same mistake. After that, I tried downloading the Notebooks again, but also got the same error. I also have enough disk space.

Would you have something else in Mind?

Thanks in advance

**Comment by zivy** [comment]
I think you misunderstood me, there was no need to download the notebooks again. The data is downloaded when needed by the notebook (fetch_data) from our data stores. Please see that the "Data" directory is empty except for the manifest.json file. I'd like you to try and download all of the notebook data in one go, as follows:
1. from the commandline cd to the SimpleITK notebooks repository directory.
2. Run the following script which will download the data used by all notebooks (~2Gb):
```
python Utilities/downloaddata.py Data/ Data/manifest.json
```
Once this completes successfully you should be able to run all notebooks and the fetch_data will load the images from the local cache (the "Data" directory).

Let me know if it resolves the issue.

**Comment by paulomontijo** [comment]
Thanks for the feedback. i understood it now.

I tried to do what you said and got the same mistake in the same file:

![image](https://user-images.githubusercontent.com/43051367/78580506-c3fc2100-7832-11ea-9773-77a707eb4e38.png)

**Comment by zivy** [comment]
Please remove all files and sub directories from the "Data" directory except the manifest.json. Based on the screen shot you provided there was already data there. I deleted the file ct_T1.standard from my directory and then ran the script. As you can see, when I ran the script it reports that the data was downloaded which isn't reported if the data was already there.

<img width="420" alt="Screen Shot 2020-04-06 at 12 58 18 PM" src="https://user-images.githubusercontent.com/338645/78584726-a5803080-7806-11ea-8e51-899b4d3dcc2c.png">

**Comment by paulomontijo** [comment]
Hello @zivy,

I tried deleting all the files except the manifest.json and downloading them as you said. Unfortunattely, I got the same error:

![image](https://user-images.githubusercontent.com/43051367/78751650-eac17100-7972-11ea-9e8c-c63882463e58.png)

**Comment by zivy** [comment]
Hello @paulomontijo 
For some reason I thought this was resolved (sorry). 

Given that I am unable to reproduce the issue, you can try a last resort approach.
Please go directly to our data repository and [manually download the data from there](https://data.kitware.com/#collection/57b5c9e58d777f126827f5a1/folder/57b5dd9a8d777f10f2695f37). You will have to unzip the files and place things in the "Data" directory.

**Comment by paulomontijo** [comment]
Hello @zivy,

Thanks for the answer again.

I could download the files and now I have the DICOM series and a readme.txt file.

![image](https://user-images.githubusercontent.com/43051367/79253851-28972b80-7e84-11ea-8ad4-ce270b2cf6a6.png)

Nevertheless, when i run the cell that fetches this data it output fetching readme.txt for a while and does nothing:

![image](https://user-images.githubusercontent.com/43051367/79254002-5bd9ba80-7e84-11ea-8311-1d5e14d9012c.png)

I checked the readme.txt and apparently there is no content about the series there:

![image](https://user-images.githubusercontent.com/43051367/79254095-80ce2d80-7e84-11ea-8839-0a804a79a7a4.png)

Could that be the problem?

**Comment by zivy** [comment]
Hello @paulomontijo,

The reference to the readme file is there so that the fetch_data mechanism downloads the zip file from our datastore. The function then just returns the path to the file which is changed to the directory name via `os.path.dirname`. You can modify the line to return the directory:
```
data_directory = 'path_to_simpleitk_notebooks/Data/CIRS057A_MR_CT_DICOM/'
```

**Comment by paulomontijo** [comment]
Hello @zivy,

it worked perfectly!

![image](https://user-images.githubusercontent.com/43051367/79311973-81a3a580-7efe-11ea-8b35-eac8687ac780.png)

Now I understand better how the fetch_data works and can continue to work with the Notebooks.

thank you very much for your help and patience.

**Comment by zivy** [comment]
You're welcome. Enjoy SimpleITK!
