### ISSUE TITLE
Migrate CircleCI to Github Actions

### ISSUE THREAD

**Issue by blowekamp** [InsightSoftwareConsortium/SimpleITK-Notebooks#266]
In an effort to consolidate CI platforms used across SimpleITK, the existing CircleCI PR based testing should be migrated to use GitHub actions.

**Comment by jwj019** [comment]
Github actions added via https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/pull/275.  However, CircleCI will remain in place as Github Actions takes double the time to run.  Hopefully, that time will come down as Github makes improvements to their infrastructure, but this may need to be revisited to phase out CircleCI entirely.
