### ISSUE TITLE
Can I view my 3d data like 4 grid slicer3d-like display?

### ISSUE THREAD

**Issue by hihunjin** [InsightSoftwareConsortium/SimpleITK-Notebooks#305]
Hello.
I'm using your SimpleITK-Notebooks.
I wonder your tool supports the 3d data view interactively.
![image](https://user-images.githubusercontent.com/32363064/126442152-99c53a9c-34ca-4d81-bbed-79589c33e683.png)
I'm reading your [documents](http://insightsoftwareconsortium.github.io/SimpleITK-Notebooks/), but can't find where it is.

Thanks in advance.

**Comment by hihunjin** [comment]
Note that I installed this with
```python
!pip install SimpleITK
!wget https://downloads.imagej.net/fiji/Life-Line/fiji-linux64-20151222.zip
!unzip -qo fiji-linux64-20151222.zip -d fiji-linux64-20151222
!mkdir ~/bin
!cp -r /content/fiji-linux64-20151222/Fiji.app ~/bin/
!ls ~/bin
!git clone https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks
%cd /content/SimpleITK-Notebooks/Utilities
import SimpleITK as sitk
```
```python
from __future__ import print_function
import importlib
from distutils.version import LooseVersion

# check that all packages are installed (see requirements.txt file)
required_packages = {'jupyter', 
                     'numpy',
                     'matplotlib',
                     'ipywidgets',
                     'scipy',
                     'pandas',
                     'SimpleITK'
                    }

problem_packages = list()
# Iterate over the required packages: If the package is not installed
# ignore the exception. 
for package in required_packages:
    try:
        p = importlib.import_module(package)        
    except ImportError:
        problem_packages.append(package)
    
if len(problem_packages) is 0:
    print('All is well.')
else:
    print('The following packages are required but not installed: ' \
          + ', '.join(problem_packages))
```
```python
import os
import SimpleITK as sitk

%run update_path_to_download_script
from downloaddata import fetch_data, fetch_data_all

from ipywidgets import interact

print(sitk.Version())

```
```python
sitk.Show(sitk.ReadImage(fetch_data("SimpleITK.jpg")), "SimpleITK Logo", debugOn=True)
```
```python
interact(lambda x: x, x=(0,10));
```

**Comment by zivy** [comment]
Hello @hihunjin,

The screenshot you are showing is of the [3D slicer Jupyter kernel](https://github.com/Slicer/SlicerJupyter) this is a different tool, not related to SimpleITK or the SimpleITK notebooks.

SimpleITK is an image analysis package and does not have internal support for visualization. The toolkit's notebook repository contains some visualization components useful for illustrating various aspects of SimpleITK, but they are not full fledged visualization components like 3D slicer.

If your focus is on visualization in a Jupyter notebook, then you should look at 3D slicer or if you want to implement your own, possibly [VTK](https://vtk.org/).

**Comment by hihunjin** [comment]
Thanks for kindly answer to my question.
BIG HELP!!!!!!!!!!
I really appreciate it from the bottom of my heart.
