### ISSUE TITLE
Registration not exactly repropducible

### ISSUE THREAD

**Issue by renatobellotti** [InsightSoftwareConsortium/SimpleITK-Notebooks#308]
Dear SimpleITK developers,

I'm trying to follow the example notebook from the registration and applying it to my own problem. Unfortunately, I get different results with every run: The convergence checker does not pass at the same iteration if I rerun the code multiple times. Do I need to seed something else? I guess the smoothing in the multi-resolution approach is not seeded properly.

Here is my code:

```python
# The code for this function has been adapted from:
# https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/0292eb5b19c914bf26cbfb842ff0eb26c1594437/Python/60_Registration_Introduction.ipynb

# Initialise the similarity transformation:
# The centre of rotation will be the centre of mass of the image.
initial_transform = sitk.CenteredTransformInitializer(
    ct1,
    ct2,
    sitk.Similarity3DTransform(),
    sitk.CenteredTransformInitializerFilter.MOMENTS
)

registration_method = sitk.ImageRegistrationMethod()

# Similarity metric settings.
registration_method.SetMetricAsMattesMutualInformation(numberOfHistogramBins=50)
registration_method.SetMetricSamplingStrategy(registration_method.RANDOM)
registration_method.SetMetricSamplingPercentage(0.2, seed=403927)

registration_method.SetInterpolator(sitk.sitkLinear)

# Optimizer settings.
registration_method.SetOptimizerAsGradientDescent(learningRate=0.8,
                                                  numberOfIterations=200,
                                                  convergenceMinimumValue=1e-6,
                                                  convergenceWindowSize=20)
registration_method.SetOptimizerScalesFromPhysicalShift()

# Setup for the multi-resolution framework.
registration_method.SetShrinkFactorsPerLevel(shrinkFactors=[4, 2, 1])
registration_method.SetSmoothingSigmasPerLevel(smoothingSigmas=[2, 1, 0])
registration_method.SmoothingSigmasAreSpecifiedInPhysicalUnitsOn()

# Optimise in place.
registration_method.SetInitialTransform(initial_transform, inPlace=False)

# Connect all of the observers so that we can perform plotting during registration.
logger = ConvergenceLogger(registration_method)
registration_method.AddCommand(sitk.sitkIterationEvent,
                               logger.on_iteration)

final_transform = registration_method.Execute(sitk.Cast(ct1, sitk.sitkFloat32),
                                              sitk.Cast(ct2, sitk.sitkFloat32))
```

**Comment by zivy** [comment]
Hello @renatobellotti,

Running a slightly modified version of your code, with a fixed seed as you did, leads to the "same" results. The usage of quotation marks is due to the fact that there are minor differences between consecutive runs. Generally speaking these are unavoidable, unless you are really willing to compromise on speed. The minor differences are associated with the use of multi-threading which leads to slight differences in estimating similarity metric values.

The code below will allow you to experiment with this using the two images used in that original notebook:
```
import SimpleITK as sitk

# The code for this function has been adapted from:
# https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/0292eb5b19c914bf26cbfb842ff0eb26c1594437/Python/60_Registration_Introduction.ipynb

def register(ct1, ct2):
    # Initialise the similarity transformation:
    # The centre of rotation will be the centre of mass of the image.
    initial_transform = sitk.CenteredTransformInitializer(
        ct1,
        ct2,
        sitk.Similarity3DTransform(),
        sitk.CenteredTransformInitializerFilter.MOMENTS
    )
    
    registration_method = sitk.ImageRegistrationMethod()
    
    # Similarity metric settings.
    registration_method.SetMetricAsMattesMutualInformation(numberOfHistogramBins=50)
    registration_method.SetMetricSamplingStrategy(registration_method.RANDOM)
    registration_method.SetMetricSamplingPercentage(0.2, seed=403927)
    
    registration_method.SetInterpolator(sitk.sitkLinear)
    
    # Optimizer settings.
    registration_method.SetOptimizerAsGradientDescent(learningRate=0.8,
                                                      numberOfIterations=200,
                                                      convergenceMinimumValue=1e-6,
                                                      convergenceWindowSize=20)
    registration_method.SetOptimizerScalesFromPhysicalShift()
    
    # Setup for the multi-resolution framework.
    registration_method.SetShrinkFactorsPerLevel(shrinkFactors=[4, 2, 1])
    registration_method.SetSmoothingSigmasPerLevel(smoothingSigmas=[2, 1, 0])
    registration_method.SmoothingSigmasAreSpecifiedInPhysicalUnitsOn()
    
    # Optimise in place.
    registration_method.SetInitialTransform(initial_transform, inPlace=False)
    
    final_transform = registration_method.Execute(sitk.Cast(ct1, sitk.sitkFloat32),
                                                  sitk.Cast(ct2, sitk.sitkFloat32))
    print(final_transform.GetParameters())
    print(f'Final metric value: {registration_method.GetMetricValue()}')
    print(f'Optimizer\'s stopping condition, {registration_method.GetOptimizerStopConditionDescription()}')

img1 = sitk.ReadImage('training_001_ct.mha')
img2 = sitk.ReadImage('training_001_mr_T1.mha')

# For full reproducibility set to 1
MAX_THREADS = 3
sitk.ProcessObject.SetGlobalDefaultNumberOfThreads(MAX_THREADS)

for i in range(5):
    register(img1, img2)
```

**Comment by renatobellotti** [comment]
Dear @zivy,

Thanks for your fast answer. I was able to make my code fully reproducible by setting the number of threads to 1.

I understand that parallelism introduces additional errors, but I think the ones I was getting were too big: I am trying to register CT images (they are thresholded to focus the registration on the bones), which gave me errors on the same order as the magnitude of the parameters for the similarity transform. Might this be a hint for a bug?

**Comment by zivy** [comment]
Hello @renatobellotti,

This does sound a bit strange, never encountered that level of variability after setting a fixed seed. Can you share a pair of images so that we can reproduce and further look into it? 

By the way, when you say "thresholded CT images" are these binary volumes (`input_for_registration = sitk.Cast(original_image>300, sitk.sitkFloat32)`)or are they the original HU only in the region of interest (`input_for_registration = sitk.Cast(original_image>300, sitk.sitkFloat32)*original_image`)? If binary volumes then that can potentially cause instability.

**Comment by renatobellotti** [comment]
Unfortunately I cannot share the images since they are sensitive personal data. Yes, it is binary volumes, perhaps this is the issue. I will investigate this, thanks for the hint!

**Comment by zivy** [comment]
Hi @renatobellotti,

Just a possible path forward based on past experience without looking at the specific data, so may or may not help:

With binary images the convergence range often becomes very small, so initialization becomes critical. You could insert an additional "initialization" step after the basic initialization where you convert the binary volumes to distance maps ([SignedMaurerDistanceMapImageFilter](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1SignedMaurerDistanceMapImageFilter.html)), register those and then register the original HU images limited to the ROI.
