### ISSUE TITLE
Reading .mat files

### ISSUE THREAD

**Issue by Rezwanarosen** [InsightSoftwareConsortium/SimpleITK-Notebooks#309]
How can I make SimpleITK read .mat image files ? It would be great if you can show me an example !

**Comment by zivy** [comment]
Hello @Rezwanarosen,

MATLAB files are not images they are much more complex, so SimpleITK does not support IO for this file type. Having said that, and assuming you are working in Python:
1. Use  scipy's [loadmat](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.loadmat.html) to read the mat file (`mat_data_dict = loadmat(file_name)`).
2. Extract the relevant numpy array information from the returned dictionary (assuming the relevant key is 'image', `numpy_arr = mat_data_dict['image']`).
3. Convert numpy array to SimpleITK image (`sitk.GetImageFromArray(numpy_arr, isVector=False)`).
```

**Comment by Rezwanarosen** [comment]
Can you please explain what relevant key is? If I give image as the key
it's showing keyError. Sorry for the inconvenience I'm causing to you guys,
but this project is really important to me ! TIA

**Comment by zivy** [comment]
Hello @Rezwanarosen,

What you are asking is not a SimpleITK question, it is generic Python. The `loadmat` function returns a Python dictionary, with one of the entries being the image data. To see the dictionary keys: `mat_data_dict.keys()`. The code snippet above which raised a KeyError assumed the relevant key is `image`. You will need to use the appropriate key to obtain the image data as a numpy array, don't know what it is, but if you look at the keys you'll identify it.

**Comment by Rezwanarosen** [comment]
Actually the images I am working on are raw ultrasound images saved in .mat
form. They are only readable by a special matlab function. I want to
analyze radiomic features of those files using PyRadiomics, but the
SimpleITK module can't directly read  those mat files. If you guys could
help to read the mat files with SimpleITK, I would be really grateful !

**Comment by zivy** [comment]
Hello @Rezwanarosen,

This appears to be more of a MATLAB question than a SimpleITK one. I would recommend converting the images from the mat format to a format supported by SimpleITK, e.g. nrrd. 

Possible options listed on Mathworks file exchange:
- https://www.mathworks.com/matlabcentral/fileexchange/48621-nrrdwriter-filename-matrix-pixelspacing-origin-encoding
- https://www.mathworks.com/matlabcentral/fileexchange/66658-addisonelliott-matnrrd

**Comment by Rezwanarosen** [comment]
Hi @ZivYaniv! I am thankful to you guys! I was successfully able to make
PyRadiomics able to read .mat files.
