### ISSUE TITLE
Please check order of input images to sitk.LabelOverlapMeasuresImageFilter.Execute

### ISSUE THREAD

**Issue by BennoGesierich** [InsightSoftwareConsortium/SimpleITK-Notebooks#344]
This issue concerns the Python notebook:
https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/34_Segmentation_Evaluation.ipynb

I think that the `reference_segmentation` should be the second input to `sitk.LabelOverlapMeasuresImageFilter.Execute` Otherwise false negative error and false positive error are interchanged, and the volume similarity is negative (instead of positive), if the volume of the evaluated segmentation is larger than that of the reference segmentation.

This would mean that 
`overlap_measures_filter.Execute(reference_segmentation, seg)` 
should be
`overlap_measures_filter.Execute(seg, reference_segmentation)`

**Comment by zivy** [comment]
Hello @BennoGesierich,

Thanks for the bug report, should be resolved shortly by [this PR](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/pull/346).
