### ISSUE TITLE
Warning in `00_Setup.ipynb`

### ISSUE THREAD

**Issue by habi** [InsightSoftwareConsortium/SimpleITK-Notebooks#369]
I want to get started with the notebooks and am running a local copy.
Running the first cell generates a `SyntaxWarning` about `if not len(problem_packages) is 0:`

I think this could just be `if not len(problem_packages):` and all would be well :)

**Comment by zivy** [comment]
Hello @habi,

Please provide the following details so that we can reproduce: OS, Python version.

**Comment by habi** [comment]
I'm running the notebooks examples on a fresh checkout in a fresh `conda` environment on Ubuntu 20.04.4 LTS

````
conda activate simpleitk-environment #actually_a_different_name
python --version
````
gives "Python 3.9.11"

**Comment by habi** [comment]
Oh, the code shown on http://insightsoftwareconsortium.github.io/SimpleITK-Notebooks/Python_html/00_Setup.html is *not* the same as https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blame/master/Python/00_Setup.ipynb#L62.
