### ISSUE TITLE
image registration problem

### ISSUE THREAD

**Issue by gaofan83** [InsightSoftwareConsortium/SimpleITK-Notebooks#376]
Thank you for generating these notebooks. I followed one of the tutorials for 2D image registration, but couldn't get the aligned images. (not points for matching?) Any suggestions?
Thanks.
[image_registration.pdf](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/files/9334481/image_registration.pdf)

**Comment by zivy** [comment]
Hello @gaofan83,

For future reference, please share a notebook/code on github, so that we can more easily help. Sharing a pdf makes it very hard.

If I understood correctly, the result does not yield good point correspondences when evaluated using the GUI?

For the last cell in the notebook, did you set `known_transformation=final_transform` in the ` gui.RegistrationPointDataAquisition`? Can't see this in the pdf and it is required for evaluating the registration results.

As the `RegistrationPointDataAquisition` GUI does not modify the original moving image, all we can know about the registration is that the original images have an unknown translation between them and what looks like a 45 degree angle rotation. 

What was the resulting transformation's `GetAngle()` and `GetTranslation()`?  For debugging purposes you should also resample the moving image using the `final_transform` so that it is easier to judge if registration is doing anything useful.

**Comment by gaofan83** [comment]
Sorry for uploading the pdf. Please see the attached txt file for the codes. I am new to this field, and what I need is a way to align two image files (see the tif.gz files attached). 
Thanks a lot.

[image_registration.txt](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/files/9337624/image_registration.txt)
[segment.tif.gz](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/files/9337664/segment.tif.gz)
[moving.tif.gz](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/files/9337695/moving.tif.gz)

**Comment by zivy** [comment]
Hello @gaofan83,

The challenge with this registration is that the two images have about a 90 degree rotation between them. The `CenteredTransformInitializer` only aligns the centers of the two volumes and does not deal with the rotation. This means the registration is initialized too far from the true optimum for it to successfully converge. 

There are various ways to perform the initialization. You could use a better estimate of the rotation even from visual inspection (e.g. `initial_transform.SetAngle(np.pi/2)`).

A more generic approach is to select corresponding points between the two images using a GUI:
```
moving_image = sitk.ReadImage("moving.tif", sitk.sitkFloat32)
fixed_image = sitk.ReadImage("segment.tif", sitk.sitkFloat32)

# Select corresponding points in both images (minimum two, but three or more is better)
# Click on a point in one image and then on the corresponding point in the other image.
point_acquisition_interface = gui.RegistrationPointDataAquisition(fixed_image, moving_image, figure_size=(8,4));
```

These are then used by a `LandmarkBasedTransformInitializer` to estimate an initial transformation:
```
# Use the corresponding points to initialize registration
fixed_image_points, moving_image_points = point_acquisition_interface.get_points()
fixed_image_points_flat = [c for p in fixed_image_points for c in p]
moving_image_points_flat = [c for p in moving_image_points for c in p]
transform = sitk.Euler2DTransform(
    sitk.LandmarkBasedTransformInitializer(
        sitk.Euler2DTransform(), fixed_image_points_flat, moving_image_points_flat
    )
)
```

For a detailed discussion of registration initialization see [this jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/63_Registration_Initialization.ipynb).

**Comment by gaofan83** [comment]
Hello @zivy 
Thank you for the tips. I tested the following codes to rotate the moving image:
```
initial_transform = sitk.Euler2DTransform(
    sitk.CenteredTransformInitializer(
        fixed_image,
        moving_image,
        sitk.Euler2DTransform(),
        sitk.CenteredTransformInitializerFilter.GEOMETRY,
    )
)

initial_transform.SetAngle(np.pi/2*3.2)
```
As for `point_acquisition_interface = gui.RegistrationPointDataAquisition(fixed_image, moving_image, figure_size=(8,4));` when I clicked on the image, nothing happened. Not sure why...

**Comment by zivy** [comment]
Hello @gaofan83,

For the GUI to support mouse interaction you need to use the `notebook` matplotlib backend (set at the top/beginning of the notebook):
```
%matplotlib notebook
```

**Comment by gaofan83** [comment]
@zivy Thanks a lot. It works!

**Comment by gaofan83** [comment]
@zivy  If I need a registration using isotropic scaling and rigid transformation with translation and rotation, I wonder whether I should use the following codes after selecting corresponding points between the two images:
```
fixed_image_points, moving_image_points = point_acquisition_interface.get_points()
fixed_image_points_flat = [c for p in fixed_image_points for c in p]
moving_image_points_flat = [c for p in moving_image_points for c in p]
similarity_transform = sitk.Similarity2DTransform(
    sitk.LandmarkBasedTransformInitializer(
        sitk.Similarity2DTransform(), fixed_image_points_flat, moving_image_points_flat
    )
)
```

**Comment by zivy** [comment]
Hello @gaofan83,

Unfortunately, `Similarity2DTransform` is currently not supported by the `LandmarkBasedTransformInitializer`. You will have to use a `AffineTransform`:
```
affine_transform = sitk.AffineTransform(
    sitk.LandmarkBasedTransformInitializer(
        sitk.AffineTransform(2), fixed_image_points_flat, moving_image_points_flat
    )
)
```

**Comment by gaofan83** [comment]
@zivy thanks a lot.
