### ISSUE TITLE
characterize_data.py fails save if output directory does not exist

### ISSUE THREAD

**Issue by seanreed1111** [InsightSoftwareConsortium/SimpleITK-Notebooks#392]
found this out the hard way.
suggestion:
```
# characterize_data.py
def main(argv=None):
...
+ import pathlib
+ pathlib.Path(args.output_file).parent.mkdir(parents=True, exist_ok=True) 
df.to_csv(args.output, index=False)
...
```

**Comment by zivy** [comment]
Hello @seanreed1111,

Thanks for the report. Should be addressed by [this PR](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/pull/393).

**Comment by seanreed1111** [comment]
cool looks good. Thanks for these notebooks they really make the learning
curve easier.

**Comment by zivy** [comment]
Thanks for the feedback, and helping improve the code.
