### ISSUE TITLE
How to use masks for filters

### ISSUE THREAD

**Issue by yuanpengpeng** [InsightSoftwareConsortium/SimpleITK-Notebooks#431]
tx = multiscale_demons(
    registration_algorithm=demons_filter,
    # fixed_image=images[fixed_image_index],
    fixed_image=fixed_image,
    #moving_image=images[moving_image_index],
    moving_image=moving_image,
    shrink_factors=[4, 2],
    smoothing_sigmas=[8, 4],
)
I have a piece of code that uses filters for non-rigid registration and want to use something like
registration_method.SetMetricFixedMask(fixed_mask)
registration_method.SetMetricMovingMask(moving_mask)
How to set the mask in this way?

**Comment by zivy** [comment]
Hello @yuanpengpeng,

Unfortunately, this is not a feature supported by the Demons family of algorithms (`DemonsRegistrationFilter`, `DiffeomorphicDemonsRegistrationFilter`, `FastSymmetricForcesDemonsRegistrationFilter`, `SymmetricForcesDemonsRegistrationFilter`). These filters compute a displacement field for the whole image.

**Comment by yuanpengpeng** [comment]
> Hello @yuanpengpeng,
> 
> Unfortunately, this is not a feature supported by the Demons family of algorithms (`DemonsRegistrationFilter`, `DiffeomorphicDemonsRegistrationFilter`, `FastSymmetricForcesDemonsRegistrationFilter`, `SymmetricForcesDemonsRegistrationFilter`). These filters compute a displacement field for the whole image.

If I want to use Simpleitk's Demons differently, and I want to pass the Mask of Fixed Image and Moving Image. Only the information in Mask is involved in the LOSS calculation. Is there any good method? Can I change this code myself?
