### ISSUE TITLE
Data is not detected as cached

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/SimpleITK-Notebooks#53]
When running the last cell in 00_Setup repeatedly, the downloaded data is not detected, and it is re-downloaded.

'''
fetch_data_all("Data", "Data/manifest.json")

Fetching cthead1.png
Fetching nac-hncma-atlas2013-Slicer4Version/Data/A1_grayT2.nrrd
Fetching CIRS057A_MR_CT_DICOM/readme.txt
Fetching CIRS057A_MR_CT_DICOM/readme.txt
Downloaded 96187036 of 96187036 bytes (100.00%)
Fetching B1_fixed_B2_moving0GenericAffine.mat
Fetching spherical_fiducials.mha
Fetching ct_T1.standard
Fetching B1_fixed_B2_movingComposite.h5
Fetching 2th_cthead1.png
Fetching nac-hncma-atlas2013-Slicer4Version/Data/A1_grayT1.nrrd
Fetching B1.tiff
Fetching nac-hncma-atlas2013-Slicer4Version/Data/hncma-atlas.nrrd
Fetching vm_head_rgb.mha
Fetching vm_head_mri.mha
Fetching VM1111Shrink-RGB.png
Fetching B2.tiff
Fetching coins.png
Fetching training_001_ct.mha
Fetching a_vm1108.png
Fetching SimpleITK.jpg
Fetching training_001_mr_T1.mha
'''

**Comment by zivy** [comment]
This is an issue with fetching a file which is inside an archive. Will address this.

**Comment by zivy** [comment]
The hash of archive files is now only validated after download. Please take a look at this branch and let me know if it works for you: https://github.com/zivy/SimpleITK-Notebooks/tree/downloadData
Will merge afterwards.

**Comment by thewtex** [comment]
Tested.  Did the job.  Thanks!
